// File generated by the FlutterFire CLI (https://github.com/firebase/flutterfire-cli).
// DO NOT EDIT and instead use FlutterFire's official documentation to update this file.
// https://firebase.google.com/docs/flutter/setup?platform=android

import 'dart:io';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Holds the platform-specific Firebase options required to initialize Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (!kIsWeb) {
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          return macos;
        case TargetPlatform.windows:
          throw UnsupportedError(
            'DefaultFirebaseOptions has not been configured for windows - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions has not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions has not been configured for ${defaultTargetPlatform.name}',
          );
      }
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions.web has not been configured yet',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_MESSAGING_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    iosBundleId: 'REPLACE_WITH_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_MESSAGING_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    iosBundleId: 'com.petitworks.apps.lifetaskmanager',
    androidPackageName: 'com.petitworks.apps.lifetaskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_MESSAGING_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    iosBundleId: 'com.petitworks.apps.lifetaskmanager.macos',
  );
}

// ignore: unused_import
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
